[package]
name = "alpm-sys"
version = "2.0.0"
readme = "../README.md"
authors = ["morganamilo <morganamilo@gmail.com>"]

description = "Raw bindings for libalpm"
homepage = "http://github.com/archlinux/alpm.rs"
repository = "http://github.com/archlinux/alpm.rs"
documentation = "https://docs.rs/alpm_sys"
license = "GPL-3.0"
keywords = ["archlinux", "arch", "alpm", "pacman"]
categories = ["external-ffi-bindings"]

[features]
git = []
generate = ["bindgen"]
generate-static = ["bindgen/static"]

[build-dependencies]
bindgen = { version = "0.55.1", optional = true, default-features = false, features = ["runtime"] }
