[package]
name = "alpm"
version = "1.0.0-rc2"
authors = ["morganamilo <morganamilo@gmail.com>"]
edition = "2018"

description = "Rust bindings for libalpm"
homepage = "http://github.com/Morganamilo/alpm.rs"
repository = "http://github.com/Morganamilo/alpm.rs"
documentation = "https://docs.rs/alpm"
license = "GPL-3.0"
keywords = ["archlinux", "arch", "alpm", "pacman"]
categories = ["api-bindings"]
exclude = ["tests"]

[features]
mtree = ["libarchive", "libarchive3-sys"]
git = ["alpm-sys/git"]
generate = ["alpm-sys/generate"]

[dependencies]
bitflags = "1.0.4"
libarchive = { version = "0.1.1", optional = true }
libarchive3-sys = { version = "0.1.2", optional = true }
alpm-sys = { path = "../alpm-sys", version = "1.0.0" }

[dev-dependencies]
criterion = "0.2.11"

[[bench]]
name = "list"
harness = false
