[package]
name = "alpm-utils"
version = "0.3.1"
authors = ["morganamilo <morganamilo@gmail.com>"]
edition = "2018"

description = "Helper functions for working with alpm"
homepage = "http://github.com/Morganamilo/alpm.rs"
repository = "http://github.com/Morganamilo/alpm.rs"
documentation = "https://docs.rs/alpm-utils"
license = "GPL-3.0"
keywords = ["archlinux", "arch", "alpm", "pacman"]

[features]
git = ["alpm/git"]
generate = ["alpm/generate"]

[dependencies]
alpm = { version = "0.10.0", path = "../alpm" }
