[package]
name = "alpm-utils"
version = "1.0.0"
authors = ["morganamilo <morganamilo@gmail.com>"]
edition = "2018"

description = "Helper functions for working with alpm"
homepage = "http://github.com/archlinux/alpm.rs"
repository = "http://github.com/archlinux/alpm.rs"
documentation = "https://docs.rs/alpm-utils"
license = "GPL-3.0"
keywords = ["archlinux", "arch", "alpm", "pacman"]

[features]
git = ["alpm/git"]
generate = ["alpm/generate"]
static = ["alpm/static"]
default = ["alpm", "conf"]
conf = ["pacmanconf", "alpm"]

[dependencies]
alpm = { version = "2.0.0", path = "../alpm", optional = true }
pacmanconf = { version = "1.0.0", optional = true }
