name: Alpm

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Install Packages
        run: pacman -Syu rust clang gcc --noconfirm --needed

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cargo test --features generate
        working-directory: alpm

  test-git:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Install Packages
        run: pacman -Syu rust curl clang git base-devel libarchive meson asciidoc --noconfirm fakechroot --needed

      - name: Install Pacman-git
        run: |
          git clone https://aur.archlinux.org/pacman-git
          chown -R nobody pacman-git
          cd pacman-git
          sudo -u nobody makepkg --nocheck
          sudo -u nobody makepkg --packagelist > list
          yes | pacman -U $(cat list)

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cargo test --features generate,git
        working-directory: alpm
